- src/pages/prices/ethi.jsx
- src/pages/prices/usdi.jsx
1. loading add
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recKDYCeGW&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recQEnZO6H&field=fldXv6F1uI
> fix: width fixed and loading add

- .eslintrc.json
- jest.config.js
- src/__tests__/components/Footer/__snapshots__/Footer.test.js.snap
- src/components/Footer/index.jsx
- src/utils/location.js
> chore: host url switch automatic

- src/pages/home/components/StrategyTable.jsx
> fix: path fixed

- src/__tests__/utils/number-format.test.js
- src/pages/home/components/ProportionSales.jsx
- src/pages/mine/components/MonthProfit.jsx
- src/pages/mine/ethi.jsx
- src/pages/mine/usdi.jsx
- src/utils/number-format.js
1. text update
2. number format
3. style update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recFi7eyWW&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=rece9U0g7V&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=reczhT1fr9&field=fldXv6F1uI
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=rectjwWKyM&field=fldXv6F1uI
> refactor: text update

- src/pages/mine/components/MonthProfit.jsx
> refactor: code update

- src/components/RightContent/index.jsx
- src/constants/vault.js
- src/pages/mine/components/MonthProfit.jsx
- src/pages/mine/ethi.jsx
- src/pages/reports/index.jsx
> refactor: value update

- src/pages/mine/components/MonthProfit.jsx
- src/pages/mine/ethi.jsx
- src/pages/mine/usdi.jsx
1. numeral format
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=reciZqN0cc&field=fldXv6F1uI
> refactor: numeral format

- pnpm-lock.yaml
- src/pages/reports/index.jsx
1. colume replace
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=rec1QkvddK&field=fldSMld39s
> fix: replace 'fun' with 'totalDeltaGain'

- src/pages/strategyDetail/components/ReportTable.jsx
1. add sort colume
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewpI8lyYw&record=recGKPh5Lm&field=fldSMld39s
> chore: add sort colume

- src/pages/reports/index.jsx
1. add default value
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewwAiWF2K&record=recyBiQ5hR&field=fldXv6F1uI
> fix: add default value

- src/__tests__/constants/strategies.test.js
- src/constants/strategies.js
1. aave icons add
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recLcU9q2s&field=fldSMld39s
> chore: icons add for eth

- src/pages/strategyDetail/components/ReportTable.jsx
> fix: remove param

- src/components/ChainChange/index.jsx
- src/components/ChainChange/index.less
- src/components/RightContent/index.jsx
- src/components/RightContent/index.less
- src/components/VaultChange/index.jsx
- src/components/VaultChange/index.less
- src/global.less
- src/pages/home/ethi.jsx
- src/pages/home/ethr.jsx
- src/pages/home/usdi.jsx
- src/pages/home/usdr.jsx
- add VaultChange component
- update ChainChange component
> feat: VaultChange component

- package.json
- src/__tests__/constants/vault.test.js
- src/__tests__/pages/home/components/LineChartContent/__snapshots__/LineChartContent.test.js.snap
> chore: for cicd

- src/__tests__/pages/home/components/LineChartContent/__snapshots__/LineChartContent.test.js.snap
- src/components/ChainChange/index.less
- src/components/VaultChange/index.less
- src/pages/home/components/LineChartContent.jsx
- src/pages/home/components/ProtocolAllocation.jsx
- src/pages/home/components/StrategyTable.jsx
- src/pages/home/components/TransationsTable.jsx
- src/pages/home/ethi.jsx
- src/pages/home/ethr.jsx
- src/pages/home/usdi.jsx
- src/pages/home/usdr.jsx
> fix: unify gutter between Col

- src/pages/home/ethr.jsx
- src/pages/home/index.jsx
- src/pages/home/usdr.jsx
- src/services/api-service.js
- Official APY, VerifyAPY
- ETHr
> feat: apy, ethr

- src/pages/home/ethr.jsx
- src/pages/home/usdr.jsx
> feat: reverse sample APY

- config/config.js
- src/components/VaultChange/index.jsx
> feat: change chain if pro env

- src/pages/home/ethr.jsx
- src/pages/home/usdr.jsx
> feat: update field

- src/hooks/useVaultFactoryAll.js
- src/pages/home/ethr.jsx
- src/pages/home/usdr.jsx
> fix: holders logic

- src/pages/home/ethr.jsx
- src/pages/home/usdr.jsx
> refactor: add tip

- src/pages/home/ethr.jsx
- src/pages/home/usdr.jsx
1. add title 
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recNPCx6Kd&field=fldXv6F1uI
> feature: add title

- src/components/VaultChange/index.jsx
> fix: vault change logics fixed

- src/components/RightContent/index.jsx
- src/components/RightContent/index.less
1. add "my account" button and logic going to homepage
**we must change router /mutils into /usdi in boc-web**
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recSkEvUSx&field=fldSMld39s
> feature: add "my account" button

- src/__tests__/components/ChartCard/__snapshots__/ChartCard.test.js.snap
- src/__tests__/pages/home/components/LineChartContent/__snapshots__/LineChartContent.test.js.snap
- src/components/ChartCard/index.jsx
- src/components/ChartCard/index.less
- src/components/RightContent/index.jsx
- src/components/RightContent/index.less
- src/global.less
- src/pages/home/components/IntroduceRow.jsx
- src/pages/home/components/LineChartContent.jsx
- src/pages/home/components/ProtocolAllocation.jsx
- src/pages/home/components/StrategyTable.jsx
- src/pages/home/components/TransationsTable.jsx
- src/pages/home/ethi.jsx
- src/pages/home/style.less
- src/pages/home/usdi.jsx
- update page layout
- update Card style
- update header button style
> style: layout, card, button

- src/pages/strategyDetail/index.jsx
- src/pages/strategyDetail/style.less
update strategy base info style
> style: strategy base info

- src/pages/strategyDetail/components/ReportTable.jsx
> code merge

- src/pages/strategyDetail/components/ReportTable.jsx
- src/pages/strategyDetail/components/StrategyApyTable.jsx
- src/pages/strategyDetail/components/style.less
- src/pages/strategyDetail/index.jsx
- src/pages/strategyDetail/style.less
> style: detail page card

- src/pages/reports/index.jsx
1. decimals update for gas fee data
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblS8STLMSlS4f8a&view=vewoKchwWv&record=recMA7GPfw&field=fldXv6F1uI
> fix: decimals update

- src/hooks/useAdminRole.js
1. vault contract function upgrade
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?table=tblCtBZFMOdx67gt&view=vewHxmlOEQ&record=recrr8NzHq&field=fldSMld39s
> feature: isVaultOrGovOrDelegate function upgrade

- src/__tests__/components/Footer/__snapshots__/Footer.test.js.snap
- src/__tests__/constants/strategies.test.js
- src/pages/reports/index.jsx
1. allocation profits logic update
> fix: Allocation Profit logics update

- src/pages/strategyDetail/index.jsx
1. add allow-withdraw-assets
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=reckqnf10L&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
> feature: add allow-withdraw-assets in strategyDetails

- src/pages/strategyDetail/index.jsx
> fix: format update

- src/pages/home/components/StrategyTable.jsx
- src/pages/strategyDetail/components/StrategyApyTable.jsx
1. text update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recOwhjJOE&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recObLpATI&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
> fix: text update

- src/components/RightContent/index.jsx
1. docs url update
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recMZFc8EO&table=tblS8STLMSlS4f8a&view=vewoKchwWv
> chore: docs url update

- src/components/RightContent/index.jsx
Reverts Bank-Of-Chain/boc-dashboard#176
> Revert "chore: docs url update"

- src/pages/reports/index.jsx
1. add sort codes for apr(before)
> feature: add sort codes for apr before

- .github/workflows/release.yml
> chore: node v16 setted

- src/pages/strategyDetail/components/PositionDetails.jsx
- src/pages/strategyDetail/components/TokenRatio.jsx
1. Fixed an bug with tooltip errors after hidden some chart lends
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recBYum0SE&table=tblS8STLMSlS4f8a&view=vewoKchwWv
> fix: Fixed an bug with tooltip errors after hidden some chart lends

- src/pages/strategyDetail/components/UniswapV3PositionDetails.jsx
> fix: space removed

- .github/workflows/testcases.yml
- src/pages/home/ethi.jsx
- src/pages/home/usdi.jsx
- src/services/dashboard-service.js
- yarn.lock
1. tvl logics upgrade
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldXv6F1uI&record=recNGlwoGW&table=tblS8STLMSlS4f8a&view=vewoKchwWv
> fix: totalAssetsIncludeVaultBuffer add for tvl

- .github/workflows/testcases.yml
- src/components/VaultChange/index.less
- src/constants/notice.js
- src/pages/home/ethi.jsx
- src/pages/home/usdi.jsx
1. notices add in dashboard home page for ethi/usdi
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recVcMHdGz&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
> feature: notices add in home page

- src/components/RightContent/index.jsx
- src/constants/strategies.js
- src/pages/home/components/ProportionSales.jsx
- src/pages/home/components/ProtocolAllocation.jsx
- src/pages/home/components/StrategyTable.jsx
- src/pages/home/components/TopSearch.jsx
- src/pages/home/ethi.jsx
- src/pages/home/usdi.jsx
1. strategy icon upgrade
2. "My Account" button removed
> fix: strategy icons fixed

- src/app.jsx
1. add beta text
https://kwg0zq6ee2.feishu.cn/base/bascnlsin3EujcBQ9DCyYa8Xsle?field=fldSMld39s&record=recdmUEAAc&table=tblCtBZFMOdx67gt&view=vewHxmlOEQ
> feature: add beta text beside logo

- src/pages/home/components/ProportionSales.jsx
- src/pages/home/components/TopSearch.jsx
- src/pages/home/ethi.jsx
- src/pages/home/usdi.jsx
> fix: bug fixed

- src/pages/home/ethi.jsx
- src/pages/home/usdi.jsx
- src/services/api-service.js
> feature: add virtual apy by monthly

- src/__tests__/constants/wallet.test.js
- src/constants/wallet.js
1. WalletConnect item hidden
https://kwg0zq6ee2.feishu.cn/base/SJbnbxOsDacZUksewcbchelWnPe?field=fldSMld39s&record=recNsrE9ay&table=tblMJW15M07PMU5r&view=vewKGNlc0a
> chore: hidden WalletConnect item
